jira_callback:
    path: /jira/callback
    controller: App\Controller\JiraController::callback
    methods: [POST]
    defaults:
        _format: json

get_task:
    path: /jira/gettask/{taskKey}
    controller: App\Controller\JiraController::getTask
    methods: [GET]
    defaults:
        _format: json
