# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Регистрируем консольные команды
    App\Command\:
        resource: '../src/Command/'
        public: true
        tags: ['console.command']

    App\Command\TestCommand:
        class: App\Command\TestCommand
        public: true
        arguments:
            - '@App\Interface\TaskRouterInterface'
        tags: ['console.command']
    
    # Регистрируем все контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    # Регистрируем сервисы 
    App\Service\:
        resource: '../src/Service/'  
    
    # Явно регистрируем логгер как сервис
    Psr\Log\LoggerInterface: '@monolog.logger'      

    # Регистрируем сервисы Temporal
    Temporal\Client\GRPC\ServiceClient:
        factory: ['Temporal\Client\GRPC\ServiceClient', 'create']
        arguments:
            - '%env(TEMPORAL_GRPC_HOST)%:%env(TEMPORAL_GRPC_PORT)%'

    Temporal\Client\WorkflowClient:
        factory: ['Temporal\Client\WorkflowClient', 'create']
        arguments:
            - '@Temporal\Client\GRPC\ServiceClient'

    # Регистрируем сервисы приложения
    App\Interface\TaskTrackerInterface:
        class: App\Service\JiraService
        arguments:
            - '%env(JIRA_BASE_URL)%'
            - '%env(JIRA_TOKEN)%'
            - '@logger'

    App\Interface\TaskRouterInterface:
        class: App\Service\JiraRouterService
        arguments:
            - '@App\Interface\TaskTrackerInterface'
            - '@Temporal\Client\WorkflowClient'
            - '@logger'


      
    