# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Event dispatcher
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    # Настройка Monolog
    monolog.logger:
        class: Monolog\Logger
        arguments:
            - 'app'
        calls:
            - method: pushHandler
              arguments: ['@monolog.handler.main']
            - method: pushHandler
              arguments: ['@monolog.handler.error']
            - method: pushHandler
              arguments: ['@monolog.handler.console']

    monolog.handler.main:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%kernel.logs_dir%/app.log'
            - !php/const Monolog\Logger::DEBUG

    monolog.handler.error:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%kernel.logs_dir%/error.log'
            - !php/const Monolog\Logger::ERROR

    # monolog.handler.console:
    #     class: Monolog\Handler\ConsoleHandler
    #     arguments:
    #         - !php/const Monolog\Logger::DEBUG

    # Явно регистрируем логгер как сервис
    Psr\Log\LoggerInterface: '@monolog.logger'        

    # Регистрируем все контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    # App\Service\:
    #     resource: '../src/Service/'
    