# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Event dispatcher
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true
    
    # Регистрируем все контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service/'  

    App\Interface\TaskTrackerInterface:
        class: App\Service\JiraService
        arguments:
            - '%env(JIRA_BASE_URL)%'
            - '%env(JIRA_TOKEN)%'
            - '@logger'

    App\Interface\TaskRouterInterface:
        class: App\Service\JiraRouterService
        arguments:
            - '@Temporal\Client\WorkflowClient'
            - '@App\Interface\TaskTrackerInterface'
            - '@logger'

    # Конфигурация Temporal
    Temporal\Client\GRPC\ServiceClient:
        arguments:
            - '%env(TEMPORAL_GRPC_HOST)%' # Host of your Temporal Service
            - '%env(TEMPORAL_GRPC_PORT)%' # Port of your Temporal Service
            # - null # Optional: TLS options
            # - null # Optional: Client options
            # - null # Optional: Context options
            # - '%env(TEMPORAL_NAMESPACE)%' # Optional: Temporal Namespace

    Temporal\Client\WorkflowClient:
        arguments:
            - '@Temporal\Client\GRPC\ServiceClient'
            # - null # Optional: WorkflowClient options

    # Настройка Monolog
    monolog.logger:
        class: Monolog\Logger
        arguments:
            - 'app'
        calls:
            - method: pushHandler
              arguments: ['@monolog.handler.main']
            - method: pushHandler
              arguments: ['@monolog.handler.error']
            - method: pushHandler
              arguments: ['@monolog.handler.console']

    monolog.handler.main:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%kernel.logs_dir%/app.log'
            - !php/const Monolog\Logger::DEBUG

    monolog.handler.error:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%kernel.logs_dir%/error.log'
            - !php/const Monolog\Logger::ERROR

    # Явно регистрируем логгер как сервис
    Psr\Log\LoggerInterface: '@monolog.logger'        
    